"""
Setup script for FACodec dependencies.

Downloads:
1. The Amphion ns3_codec model code (FACodecEncoder, FACodecDecoder)
2. Pretrained weights from HuggingFace

Run this once before using the FACodec-based inference pipeline.

Usage:
    python setup_facodec.py
"""

import os
import sys
import subprocess
import shutil

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
AMPHION_DIR = os.path.join(SCRIPT_DIR, "amphion_codec")
NS3_CODEC_DIR = os.path.join(AMPHION_DIR, "ns3_codec")


def clone_amphion_codec():
    """Sparse-clone only the ns3_codec module from Amphion."""
    if os.path.isdir(NS3_CODEC_DIR) and os.path.isfile(
        os.path.join(NS3_CODEC_DIR, "facodec.py")
    ):
        print(f"[INFO] Amphion ns3_codec already exists at {NS3_CODEC_DIR}")
        return

    print("[INFO] Downloading Amphion ns3_codec module...")
    os.makedirs(AMPHION_DIR, exist_ok=True)

    # Clone with sparse checkout to get only the codec module
    temp_clone = os.path.join(SCRIPT_DIR, "_amphion_temp")
    if os.path.isdir(temp_clone):
        shutil.rmtree(temp_clone)

    try:
        subprocess.run(
            [
                "git", "clone", "--depth", "1", "--filter=blob:none",
                "--sparse", "https://github.com/open-mmlab/Amphion.git",
                temp_clone,
            ],
            check=True,
        )
        subprocess.run(
            ["git", "sparse-checkout", "set", "models/codec/ns3_codec"],
            cwd=temp_clone,
            check=True,
        )

        # Copy the codec module to our target location
        src = os.path.join(temp_clone, "models", "codec", "ns3_codec")
        if os.path.isdir(NS3_CODEC_DIR):
            shutil.rmtree(NS3_CODEC_DIR)
        shutil.copytree(src, NS3_CODEC_DIR)
        print(f"[INFO] Copied ns3_codec to {NS3_CODEC_DIR}")

    finally:
        # Clean up temp clone
        if os.path.isdir(temp_clone):
            shutil.rmtree(temp_clone, ignore_errors=True)

    # Create __init__.py in amphion_codec to make it importable
    init_path = os.path.join(AMPHION_DIR, "__init__.py")
    if not os.path.isfile(init_path):
        with open(init_path, "w") as f:
            f.write("# Auto-generated by setup_facodec.py\n")


def download_pretrained_weights():
    """Download pretrained FACodec weights from HuggingFace."""
    weights_dir = os.path.join(SCRIPT_DIR, "facodec_weights")
    os.makedirs(weights_dir, exist_ok=True)

    encoder_path = os.path.join(weights_dir, "ns3_facodec_encoder.bin")
    decoder_path = os.path.join(weights_dir, "ns3_facodec_decoder.bin")

    if os.path.isfile(encoder_path) and os.path.isfile(decoder_path):
        print(f"[INFO] Pretrained weights already exist at {weights_dir}")
        return

    print("[INFO] Downloading pretrained FACodec weights from HuggingFace...")
    try:
        from huggingface_hub import hf_hub_download

        hf_hub_download(
            repo_id="amphion/naturalspeech3_facodec",
            filename="ns3_facodec_encoder.bin",
            local_dir=weights_dir,
        )
        hf_hub_download(
            repo_id="amphion/naturalspeech3_facodec",
            filename="ns3_facodec_decoder.bin",
            local_dir=weights_dir,
        )
        print(f"[INFO] Weights downloaded to {weights_dir}")

    except ImportError:
        print("[ERROR] huggingface_hub not installed. Run: pip install huggingface_hub")
        sys.exit(1)


def install_dependencies():
    """Install required Python packages."""
    packages = ["huggingface_hub", "einops"]
    for pkg in packages:
        try:
            __import__(pkg)
            print(f"[INFO] {pkg} already installed")
        except ImportError:
            print(f"[INFO] Installing {pkg}...")
            subprocess.run(
                [sys.executable, "-m", "pip", "install", pkg],
                check=True,
            )


if __name__ == "__main__":
    print("=" * 60)
    print("FACodec Setup for ZEST Pipeline")
    print("=" * 60)

    install_dependencies()
    clone_amphion_codec()
    download_pretrained_weights()

    print("\n" + "=" * 60)
    print("Setup complete!")
    print("=" * 60)
    print(f"  Amphion codec code: {NS3_CODEC_DIR}")
    print(f"  Pretrained weights: {os.path.join(SCRIPT_DIR, 'facodec_weights')}")
    print("\nYou can now run decoder_inference.py")
